In [2]:
import numpy as np 
import pandas as pd

In [6]:
C = np.array([[1, 2, 1],
              [6, -1, 0],
              [-1, -2, -1]])

cov = np.cov(C)



In [10]:
M = np.array([[1, 2, 1], [6, -1, 0], [-1, -2, -1]])
E = np.array ([2,3,-2])
eigenvalues, eigenvectors = np.linalg.eig(M)
eigenvalues


array([-4.00000000e+00,  3.00000000e+00,  9.61673584e-17])

In [14]:
C = np.array([
    [1, 2, 1],
    [6, -1, 0],
    [-1, -2, -1]
])

# Eigenvectors (as columns of the matrix)
ev1 = np.array([1, 6, -13])
ev2 = np.array([-1, 2, 1])
ev3 = np.array([2, 3, -2])

# Calculate the eigenvalues by multiplying the covariance matrix with each eigenvector
lambda_ev1 = np.dot(C, ev1) / ev1
lambda_ev2 = np.dot(C, ev2) / ev2
lambda_ev3 = np.dot(C, ev3) / ev3

lambda_ev1, lambda_ev2, lambda_ev3

(array([ 0.,  0., -0.]), array([-4., -4., -4.]), array([3., 3., 3.]))

In [15]:
import numpy as np
from scipy.stats import poisson

# Given data
data_points = [0, 0, 1, 1]
lambda_val = 2  # Given lambda value for the Poisson distribution

# Calculate the probability for each data point using the Poisson PMF
probabilities = [poisson.pmf(x, lambda_val) for x in data_points]

# Multiply all the probabilities together to get the final probability
final_probability = np.prod(probabilities)

print("The probability of obtaining the data points [0, 0, 1, 1] is:", final_probability)


The probability of obtaining the data points [0, 0, 1, 1] is: 0.0013418505116100476


In [3]:
A = np.array([[2,1], [-1,0]])
B = np.array([[-1,1], [0,2]])
AB = np.dot(A,B)    
print(AB)

[[-2  4]
 [ 1 -1]]


In [27]:
eigenvalues, eigenvectors = np.linalg.eig(cov)
eigenvalues = np.sort(eigenvalues)[::-1]
eigenvalues = np.round(eigenvalues, 2)
eigenvectors = np.round(eigenvectors, 2)
eigenvectors

array([[-0.09,  0.71, -0.7 ],
       [ 0.99,  0.  , -0.13],
       [ 0.09,  0.71,  0.7 ]])

In [38]:
v = np.array([2, -1, 1])
w = np.array([[-1,2,1], 
             [1,6,-13]])
projection = np.dot(v, w.T)
projection

array([ -3, -17])

In [42]:

red_points = np.array([[-2, -2], [-2, 2],[ -4, 0 ], [0,0]])
blue_points = np.array([[0, 2], [2, 0], [4, 2], [2,4]])

red_centroid = np.mean(red_points, axis=0)
blue_centroid = np.mean(blue_points, axis=0)

n_red = len(red_points)
n_blue = len(blue_points)

squared_distance = np.sum((red_centroid - blue_centroid)**2)
ward_distance = squared_distance * (n_red * n_blue) / (n_red + n_blue)

print(f"Ward's distance: {ward_distance}")

Ward's distance: 40.0


In [43]:
import math

lambda_param = 2
data = [0, 0, 1, 1, 0]

def poisson_prob(k, lambda_param):
    return (lambda_param**k * math.exp(-lambda_param)) / math.factorial(k)

probability = 1
for point in data:
    probability *= poisson_prob(point, lambda_param)

print(f"Probability: {probability}")

Probability: 0.00018159971904993944
